### ISSUE TITLE
Add highlighting for code

### ISSUE THREAD

**Issue by kartik-madhak** [kartik-madhak/noter#41]
Single backticks are currently not highlighted in the editor. It is treated as simple string. 
Add functionality to make sure it is highlighted properly. Single backticks should be able to highlight one liner and make it look like a tag/badge. `Just like this`

Currently it looks like this: 
![image](https://github.com/kartik-madhak/noter/assets/58913047/8c698df7-cb4c-452e-8110-beb42134e503)

Make sure it is compatible with light/dark modes

**Comment by CrownPab** [comment]
Hello, may I be assigned this issue?

**Comment by kartik-madhak** [comment]
Definitely, thanks for taking it up!

**Comment by kartik-madhak** [comment]
Hey, any breakthroughs? I would be happy to take this up if you want!

**Comment by kartik-madhak** [comment]
Taking this up since it's up for too long

**Comment by kartik-madhak** [comment]
#81 solves this
