### ISSUE TITLE
Make file view in sidebar centered

### ISSUE THREAD

**Issue by kartik-madhak** [kartik-madhak/noter#43]
![image](https://github.com/kartik-madhak/noter/assets/58913047/64858f4e-03b3-492a-8cc1-8f8e865b76da)
Currently the file icon and name are not perfectly vertically centered when selected. Make them centered

**Comment by Abhishek2nayak** [comment]
@kartik-madhak i want to fix this issue. Assign this issue to me.

**Comment by kartik-madhak** [comment]
Great! I have assigned it to you, let me know if you are facing any problems!

**Comment by Abhishek2nayak** [comment]
@kartik-madhak I encounter some problem. whenever I am trying to create new file, the page got turned into white. I am not undestand why this happening. Please help me.

**Comment by kartik-madhak** [comment]
That is weird, could you tell me what is your system configuration? Also did you follow the steps mentioned in the readme?

If yes, open the console by right clicking on the app, clicking on the inspect element menu and going to the console tab. After that, try creating a new file again and check what is the error in the console.

**Comment by kartik-madhak** [comment]
Hey @Abhishek2nayak, were you able to solve the issue?

**Comment by Abhishek2nayak** [comment]
Apologies, @kartik-madhak , for the delay in addressing this matter. My university exams required my full attention, but I am now ready to dedicate my efforts to resolving the issue.

**Comment by kartik-madhak** [comment]
Hey! Did you had any success running the app properly? 
Let me know otherwise I can pick this issue!
@Abhishek2nayak

**Comment by kartik-madhak** [comment]
Closing this since this seems to be solved at some point
