### ISSUE TITLE
Make the editor zoomable using `ctrl` + `+/-`

### ISSUE THREAD

**Issue by kartik-madhak** [kartik-madhak/noter#45]
This is kinda expected behavior from all the text editors. Font should be zoomable via `ctrl` + `+/-` keybinding. Currently, the editor font can only be changed with `ctrl` + `mouse scroll`.

Make sure it works across all OSs - Windows, Linux, and macOS

**Comment by taran1326** [comment]
Hey I want to solve this issue but I need a little help here , What is the tech stack you are using here ?

**Comment by kartik-madhak** [comment]
Hey there, welcome!
The tech stack is Tauri - React (with Vite)  (and Chakra UI) + Rust
There is a readme file at the repo home which has setup instructions, let me know if you are having any difficulty!

**Comment by Tobshub** [comment]
hi, I'd like to work on this

**Comment by kartik-madhak** [comment]
Great, assigning it to you @Tobshub!

**Comment by kartik-madhak** [comment]
@taran1326 there is #44 which is a similar issue if you wanna take a look!
