### ISSUE TITLE
Pressing Enter on any modal should submit the modal's main function

### ISSUE THREAD

**Issue by kartik-madhak** [kartik-madhak/noter#50]
Implement #40 for rename and delete modal

<details open>
<summary>Checklist</summary>

- [X] Modify `src/components/Sidebar/RenameModal.tsx` ✓ https://github.com/kartik-madhak/noter/commit/871d2f8da5ee3923d4dc49e618b378af5d67e41a
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Modify `src/components/Sidebar/RenameModal.tsx` ✓ https://github.com/kartik-madhak/noter/commit/d840ca065a717c81b049c02038f652f0c673db60
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Modify `src/components/Sidebar/RenameModal.tsx` ✓ https://github.com/kartik-madhak/noter/commit/c8984aebdf417f7d751c4c433b8e91011826ad3f
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Modify `src/components/Sidebar/RenameModal.tsx` ✓ https://github.com/kartik-madhak/noter/commit/5039f293e9adb86ac45beca187477b18f7671e62
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Modify `src/components/Sidebar/RenameModal.tsx` ! No changes made
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Check `src/components/Sidebar/RenameModal.tsx` ✗
- [X] Modify `src/components/Sidebar/DeleteModal.tsx` ✓ https://github.com/kartik-madhak/noter/commit/97396fc4973d87e9e6fe0ee7ead3d9e87753151f
- [X] Check `src/components/Sidebar/DeleteModal.tsx` ✗
- [X] Modify `src/components/Sidebar/DeleteModal.tsx` ✓ https://github.com/kartik-madhak/noter/commit/8c09cd93c9b3163bd5c46f909091e5985f71305f
- [X] Check `src/components/Sidebar/DeleteModal.tsx` ✗
- [X] Modify `src/components/Sidebar/DeleteModal.tsx` ✓ https://github.com/kartik-madhak/noter/commit/ccb8bad6aca2fbc68fed17bea7bde4b2705208c4
- [X] Check `src/components/Sidebar/DeleteModal.tsx` ✗
- [ ] Modify `src/components/Sidebar/DeleteModal.tsx` ⋯
- [ ] Check `src/components/Sidebar/DeleteModal.tsx` ▶
- [ ] Check `src/components/Sidebar/DeleteModal.tsx` ▶
- [ ] Check `src/components/Sidebar/DeleteModal.tsx` ▶

![Flowchart](http://24.199.78.105:8082/public/cb6d3dae14add32cdbd8d9d05d9a597b781cccaa5e6bf5d040957c86e8f63a9f_50_flowchart.svg)
</details>

**Comment by Parth699** [comment]
I am working on this
