### ISSUE TITLE
Add a settings sidebar

### ISSUE THREAD

**Issue by kartik-madhak** [kartik-madhak/noter#52]
Too many buttons on the navbar. Add them to the sidebar that opens to the right.

**Comment by AnuraagReddy123** [comment]
Hey can I work on this issue? I am new to Typescript so would it be too difficult?

**Comment by kartik-madhak** [comment]
Sure thing, I have made the requirements simpler, should be much easier now! Let me know if you have any questions...
I am assigning you this issue.

**Comment by kartik-madhak** [comment]
Taking this up since it has been up for a long time!
